[source]
type = "N2N"
address = ["Tcp", "relays-new.cardano-mainnet.iohk.io:3001"]
magic = "mainnet"

[source.mapper]
include_transaction_details = true

[[filters]]
type = "Fingerprint"

[sink]
type = "Elastic"
url = "https://localhost:9200"
index = "oura.sink.v0.mainnet"
idempotency = true

[sink.credentials]
type = "Basic"
username = "elastic"
password = "your secret password"